version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Login with ecr credentials"
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION  --no-include-email)
  build:
    commands:
      - echo "Building images..."
      - docker build . -t $DOCKER_IMAGE:latest
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ];
        then
        echo "Pushing images to ecs docker repository";
        docker push $DOCKER_IMAGE:latest;
        else
        echo 'Build failed ignoring deployment';
        fi
